feat: use react-attach-handler module instead of own event attaching …
sylvesteraswin/react-gallery-swiper pull request #2
Opened 2016-12-14 11:29 UTC by lucidNTR

…and use id scopes for the sliders key events

2016-12-14 11:30 UTC, lucidNTR commented on src/GallerySwiper.jsx
> +                    target={BASE_CLASS}
@sylvesteraswin any ideo how to create id names so there are no problems with multiple instances?

2016-12-14 11:37 UTC, lucidNTR commented on src/GallerySwiper.jsx
> +                    target={BASE_CLASS}
if you dont have a better idea i will generate https://lodash.com/docs/4.17.2#uniqueId a unique id on the component will mount event and add that to the  base_class

2016-12-14 11:58 UTC, sylvesteraswin requested changes

2016-12-14 11:58 UTC, sylvesteraswin commented on src/GallerySwiper.jsx
> +                    target={BASE_CLASS}
@lucidNTR you just use a simple uid using a random number and add to to state when the component mounts.

2016-12-14 15:26 UTC, sylvesteraswin requested changes

2016-12-14 15:26 UTC, sylvesteraswin commented on src/GallerySwiper.jsx
> +                    target={BASE_CLASS + this.state.id}
please use ` to concat variables.

2016-12-14 15:32 UTC, lucidNTR commented
@sylvesteraswin used math random for id generation as you requested and string literals, ready for review now

2016-12-14 15:35 UTC, lucidNTR commented
also sorry for the typos in the commit message, just saw them :-(

2016-12-15 12:48 UTC, sylvesteraswin approved these changes

2016-12-15 12:48 UTC, merged